const data = [
  {title:'居家',viewImg:'http://t.cn/RSVQylD',
  viewData:[
    {name:'夏凉',img:'http://t.cn/RSVWlQb'},
    {name:'被枕',img:'http://t.cn/RSVW1Op'},
    {name:'床品件套',img:'http://t.cn/RSVlPdZ'},
    {name:'布艺软装',img:'http://t.cn/RSVlyCR'},
    {name:'家具',img:'http://t.cn/RSVlcmT'},
    {name:'灯具',img:'http://t.cn/RSVl6sE'},
    {name:'家饰',img:'http://t.cn/RSVlpFo'},
    {name:'宠物',img:'http://t.cn/RSVlQzO'}
  ]},
  {title:'餐厨',viewImg:'http://t.cn/RSVQfO0',
  viewData:[
    {name:'锅具',img:'http://t.cn/RSVlDif'},
    {name:'杯壶',img:'http://t.cn/RSVj7mm'},
    {name:'功能餐具',img:'http://t.cn/RSVj5fh'},
    {name:'餐具',img:'http://t.cn/RSVjxGa'},
    {name:'茶具咖啡具',img:'http://t.cn/RSVjCVq'},
    {name:'清洁保鲜',img:'http://t.cn/RSVjYJl'},
    {name:'刀剪砧板',img:'http://t.cn/RSVjunU'},
    {name:'厨房小电',img:'http://t.cn/RSVYhhu'}
  ]},
  {title:'配件',viewImg:'http://t.cn/RSVQylD',
  viewData:[
    {name:'夏凉',img:'http://t.cn/RSVWlQb'},
    {name:'被枕',img:'http://t.cn/RSVW1Op'},
    {name:'床品件套',img:'http://t.cn/RSVlPdZ'},
    {name:'布艺软装',img:'http://t.cn/RSVlyCR'},
    {name:'家具',img:'http://t.cn/RSVlcmT'},
    {name:'灯具',img:'http://t.cn/RSVl6sE'},
    {name:'家饰',img:'http://t.cn/RSVlpFo'},
    {name:'宠物',img:'http://t.cn/RSVlQzO'}
  ]},
  {title:'服装',viewImg:'http://t.cn/RSVQfO0',
  viewData:[
    {name:'锅具',img:'http://t.cn/RSVlDif'},
    {name:'杯壶',img:'http://t.cn/RSVj7mm'},
    {name:'功能餐具',img:'http://t.cn/RSVj5fh'},
    {name:'餐具',img:'http://t.cn/RSVjxGa'},
    {name:'茶具咖啡具',img:'http://t.cn/RSVjCVq'},
    {name:'清洁保鲜',img:'http://t.cn/RSVjYJl'},
    {name:'刀剪砧板',img:'http://t.cn/RSVjunU'},
    {name:'厨房小电',img:'http://t.cn/RSVYhhu'}
  ]},
  {title:'洗护',viewImg:'http://t.cn/RSVQfO0',
  viewData:[
    {name:'锅具',img:'http://t.cn/RSVlDif'},
    {name:'杯壶',img:'http://t.cn/RSVj7mm'},
    {name:'功能餐具',img:'http://t.cn/RSVj5fh'},
    {name:'餐具',img:'http://t.cn/RSVjxGa'},
    {name:'茶具咖啡具',img:'http://t.cn/RSVjCVq'},
    {name:'清洁保鲜',img:'http://t.cn/RSVjYJl'},
    {name:'刀剪砧板',img:'http://t.cn/RSVjunU'},
    {name:'厨房小电',img:'http://t.cn/RSVYhhu'}
  ]},
  {title:'婴童',viewImg:'http://t.cn/RSVQylD',
  viewData:[
    {name:'夏凉',img:'http://t.cn/RSVWlQb'},
    {name:'被枕',img:'http://t.cn/RSVW1Op'},
    {name:'床品件套',img:'http://t.cn/RSVlPdZ'},
    {name:'布艺软装',img:'http://t.cn/RSVlyCR'},
    {name:'家具',img:'http://t.cn/RSVlcmT'},
    {name:'灯具',img:'http://t.cn/RSVl6sE'},
    {name:'家饰',img:'http://t.cn/RSVlpFo'},
    {name:'宠物',img:'http://t.cn/RSVlQzO'}
  ]},
  {title:'杂货',viewImg:'http://t.cn/RSVQfO0',
  viewData:[
    {name:'锅具',img:'http://t.cn/RSVlDif'},
    {name:'杯壶',img:'http://t.cn/RSVj7mm'},
    {name:'功能餐具',img:'http://t.cn/RSVj5fh'},
    {name:'餐具',img:'http://t.cn/RSVjxGa'},
    {name:'茶具咖啡具',img:'http://t.cn/RSVjCVq'},
    {name:'清洁保鲜',img:'http://t.cn/RSVjYJl'},
    {name:'刀剪砧板',img:'http://t.cn/RSVjunU'},
    {name:'厨房小电',img:'http://t.cn/RSVYhhu'}
  ]},
  {title:'饮食',viewImg:'http://t.cn/RSVQylD',
  viewData:[
    {name:'夏凉',img:'http://t.cn/RSVWlQb'},
    {name:'被枕',img:'http://t.cn/RSVW1Op'},
    {name:'床品件套',img:'http://t.cn/RSVlPdZ'},
    {name:'布艺软装',img:'http://t.cn/RSVlyCR'},
    {name:'家具',img:'http://t.cn/RSVlcmT'},
    {name:'灯具',img:'http://t.cn/RSVl6sE'},
    {name:'家饰',img:'http://t.cn/RSVlpFo'},
    {name:'宠物',img:'http://t.cn/RSVlQzO'}
  ]},
  {title:'志趣',viewImg:'http://t.cn/RSVQfO0',
  viewData:[
    {name:'锅具',img:'http://t.cn/RSVlDif'},
    {name:'杯壶',img:'http://t.cn/RSVj7mm'},
    {name:'功能餐具',img:'http://t.cn/RSVj5fh'},
    {name:'餐具',img:'http://t.cn/RSVjxGa'},
    {name:'茶具咖啡具',img:'http://t.cn/RSVjCVq'},
    {name:'清洁保鲜',img:'http://t.cn/RSVjYJl'},
    {name:'刀剪砧板',img:'http://t.cn/RSVjunU'},
    {name:'厨房小电',img:'http://t.cn/RSVYhhu'}
  ]}
]

export default data
